2025-04-04 23:40:34,134 [INFO] ‚úÖ App started
2025-04-04 23:40:34,134 [INFO] ‚úÖ Starting status_updater thread
2025-04-04 23:43:27,144 [INFO] üî¥ App shutting down...
2025-04-04 23:43:51,707 [INFO] ‚úÖ App started
2025-04-04 23:43:51,707 [INFO] ‚úÖ Starting status_updater thread
2025-04-04 23:46:50,166 [INFO] üî¥ App shutting down...
2025-04-04 23:50:24,835 [ERROR] Task exception was never retrieved
future: <Task finished name='Task-13' coro=<Server.serve() done, defined at C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py:68> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 32, in run
    return loop.run_until_complete(future)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 339, in __wakeup
    self.__step()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
2025-04-04 23:50:44,505 [INFO] ‚úÖ App started
2025-04-04 23:50:44,506 [INFO] ‚úÖ Starting status_updater thread
2025-04-04 23:53:17,969 [INFO] üî¥ App shutting down...
2025-04-04 23:53:18,004 [INFO] ‚úÖ App started
2025-04-04 23:53:18,004 [INFO] ‚úÖ Starting status_updater thread
2025-04-04 23:53:21,603 [INFO] üî¥ App shutting down...
2025-04-04 23:54:21,874 [ERROR] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Server.serve() done, defined at C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py:68> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 32, in run
    return loop.run_until_complete(future)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 339, in __wakeup
    self.__step()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
2025-04-04 23:54:21,875 [ERROR] Task exception was never retrieved
future: <Task finished name='Task-29' coro=<Server.serve() done, defined at C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py:68> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 32, in run
    return loop.run_until_complete(future)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 339, in __wakeup
    self.__step()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
2025-04-04 23:54:21,875 [ERROR] Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Server.serve() done, defined at C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py:68> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 32, in run
    return loop.run_until_complete(future)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 64, in run_until_complete
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 339, in __wakeup
    self.__step()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\uvicorn\server.py", line 330, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
2025-04-05 00:01:06,022 [INFO] ‚úÖ App started
2025-04-05 00:01:06,023 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 09:49:09,372 [INFO] ‚úÖ App started
2025-04-05 09:49:09,374 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 09:50:09,744 [INFO] ‚úÖ App started
2025-04-05 09:50:09,744 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 09:52:40,008 [INFO] ‚úÖ App started
2025-04-05 09:52:40,008 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 09:54:14,945 [INFO] ‚úÖ App started
2025-04-05 09:54:14,945 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 09:56:53,343 [INFO] ‚úÖ App started
2025-04-05 09:56:53,344 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 09:59:37,974 [ERROR] ‚ùó Error occurred: '<' not supported between instances of 'dict' and 'dict'
2025-04-05 10:34:50,052 [INFO] ‚úÖ App started
2025-04-05 10:34:50,052 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 10:35:40,864 [ERROR] ‚ùó Error occurred: Expecting value: line 2 column 1 (char 2)
2025-04-05 10:36:05,380 [ERROR] ‚ùó Error occurred: Expecting value: line 2 column 1 (char 2)
2025-04-05 10:45:59,970 [INFO] ‚úÖ App started
2025-04-05 10:45:59,971 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 11:00:58,344 [INFO] ‚úÖ App started
2025-04-05 11:00:58,345 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 11:15:12,609 [INFO] ‚úÖ App started
2025-04-05 11:15:12,610 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 12:24:08,558 [INFO] ‚úÖ App started
2025-04-05 12:24:08,560 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 12:39:30,098 [INFO] ‚úÖ App started
2025-04-05 12:39:30,101 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 12:42:14,306 [ERROR] ‚ùó Error occurred: 'default_tickers' is undefined
2025-04-05 12:42:16,367 [ERROR] ‚ùó Error occurred: 'default_tickers' is undefined
2025-04-05 12:45:45,255 [INFO] ‚úÖ App started
2025-04-05 12:45:45,256 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 13:04:25,929 [INFO] ‚úÖ App started
2025-04-05 13:04:25,932 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 13:06:02,636 [INFO] ‚úÖ App started
2025-04-05 13:06:02,637 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 13:33:20,597 [INFO] ‚úÖ App started
2025-04-05 13:33:20,599 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 13:53:19,293 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-05 13:53:20,514 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-05 13:53:59,224 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-05 13:54:13,291 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-05 13:57:17,034 [INFO] ‚úÖ App started
2025-04-05 13:57:17,036 [INFO] ‚úÖ Starting status_updater thread
2025-04-05 13:58:48,885 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-05 13:58:50,095 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-05 14:10:48,557 [INFO] ‚úÖ App started
2025-04-05 14:10:48,560 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 20:33:09,937 [INFO] ‚úÖ App started
2025-04-06 20:33:09,939 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 20:37:50,245 [INFO] ‚úÖ App started
2025-04-06 20:37:50,246 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 20:39:33,436 [ERROR] ‚ùó Error occurred: name 'FileResponse' is not defined
2025-04-06 20:39:44,638 [ERROR] ‚ùó Error occurred: name 'FileResponse' is not defined
2025-04-06 20:42:17,770 [ERROR] ‚ùó Error occurred: name 'FileResponse' is not defined
2025-04-06 20:45:01,939 [INFO] ‚úÖ App started
2025-04-06 20:45:01,940 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 20:50:46,381 [INFO] ‚úÖ App started
2025-04-06 20:50:46,381 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 21:06:48,634 [INFO] ‚úÖ App started
2025-04-06 21:06:48,636 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 21:07:50,121 [INFO] ‚úÖ App started
2025-04-06 21:07:50,124 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 21:11:56,379 [INFO] ‚úÖ App started
2025-04-06 21:11:56,381 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 21:19:15,219 [INFO] ‚úÖ App started
2025-04-06 21:19:15,221 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 21:25:50,490 [ERROR] ‚ùó Error occurred: orderbook_view.html
2025-04-06 21:26:07,450 [ERROR] ‚ùó Error occurred: orderbook_view.html
2025-04-06 21:28:14,782 [ERROR] ‚ùó Error occurred: expected token 'end of statement block', got 'with'
2025-04-06 21:28:15,938 [ERROR] ‚ùó Error occurred: expected token 'end of statement block', got 'with'
2025-04-06 21:28:37,267 [INFO] ‚úÖ App started
2025-04-06 21:28:37,270 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 21:29:11,476 [ERROR] ‚ùó Error occurred: expected token 'end of statement block', got 'with'
2025-04-06 21:30:33,921 [ERROR] ‚ùó Error occurred: base.html
2025-04-06 21:30:34,795 [ERROR] ‚ùó Error occurred: base.html
2025-04-06 21:46:59,886 [INFO] ‚úÖ App started
2025-04-06 21:46:59,887 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 21:57:48,001 [INFO] ‚úÖ App started
2025-04-06 21:57:48,003 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 21:58:24,813 [ERROR] ‚ùó Error occurred: 'tickers_data' is undefined
2025-04-06 22:06:29,858 [INFO] ‚úÖ App started
2025-04-06 22:06:29,859 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 22:18:51,754 [ERROR] ‚ùó Error occurred: 'tickers_data' is undefined
2025-04-06 22:20:16,050 [INFO] ‚úÖ App started
2025-04-06 22:20:16,052 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 22:20:34,053 [ERROR] ‚ùó Error occurred: name 'sorted_tickers' is not defined
2025-04-06 22:22:39,854 [INFO] ‚úÖ App started
2025-04-06 22:22:39,855 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 22:23:55,684 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-06 22:23:56,990 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-06 22:30:12,095 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-06 22:30:15,840 [ERROR] ‚ùó Error occurred: name 'selected_tickers' is not defined
2025-04-06 22:30:49,058 [INFO] ‚úÖ App started
2025-04-06 22:30:49,060 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 22:31:13,413 [ERROR] ‚ùó Error occurred: 'tickers_data' is undefined
2025-04-06 22:32:16,275 [ERROR] ‚ùó Error occurred: base.html
2025-04-06 22:43:10,797 [INFO] ‚úÖ App started
2025-04-06 22:43:10,798 [INFO] ‚úÖ Starting status_updater thread
2025-04-06 22:50:01,615 [INFO] ‚úÖ App started
2025-04-06 22:50:01,616 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 01:02:14,845 [INFO] ‚úÖ App started
2025-04-07 01:02:14,846 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 01:02:34,995 [ERROR] ‚ùó Error occurred: name 'HTMLResponse' is not defined
2025-04-07 01:06:10,160 [ERROR] ‚ùó Error occurred: name 'tickers_by_exchange' is not defined
2025-04-07 01:06:10,297 [ERROR] ‚ùó Error occurred: name 'FileResponse' is not defined
2025-04-07 01:08:39,470 [INFO] ‚úÖ App started
2025-04-07 01:08:39,471 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 01:10:54,446 [ERROR] ‚ùó Error occurred: name 'tickers_by_exchange' is not defined
2025-04-07 01:10:54,483 [ERROR] ‚ùó Error occurred: name 'FileResponse' is not defined
2025-04-07 01:10:55,181 [ERROR] ‚ùó Error occurred: name 'tickers_by_exchange' is not defined
2025-04-07 01:10:55,482 [ERROR] ‚ùó Error occurred: name 'FileResponse' is not defined
2025-04-07 01:11:50,299 [INFO] ‚úÖ App started
2025-04-07 01:11:50,300 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 01:12:08,295 [ERROR] ‚ùó Error occurred: name 'tickers_by_exchange' is not defined
2025-04-07 01:18:31,278 [INFO] ‚úÖ App started
2025-04-07 01:18:31,280 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 01:18:40,754 [ERROR] ‚ùó Error occurred: no filter named 'enumerate'
2025-04-07 01:21:18,464 [ERROR] ‚ùó Error occurred: no filter named 'enumerate'
2025-04-07 01:26:25,595 [INFO] ‚úÖ App started
2025-04-07 01:26:25,596 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 01:41:54,245 [INFO] ‚úÖ App started
2025-04-07 01:41:54,246 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 01:42:46,665 [ERROR] ‚ùó Error occurred: Expecting value: line 2 column 1 (char 2)
2025-04-07 01:44:16,407 [ERROR] ‚ùó Error occurred: Expecting value: line 2 column 1 (char 2)
2025-04-07 02:11:33,774 [INFO] ‚úÖ App started
2025-04-07 02:11:33,775 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 02:12:39,056 [ERROR] ‚ùó Error occurred: 'NoneType' object has no attribute 'lower'
2025-04-07 02:13:10,149 [ERROR] ‚ùó Error occurred: 'NoneType' object has no attribute 'lower'
2025-04-07 02:15:29,575 [INFO] ‚úÖ App started
2025-04-07 02:15:29,576 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 02:16:43,117 [ERROR] ‚ùó Error occurred: Expecting value: line 2 column 1 (char 2)
2025-04-07 02:31:36,898 [INFO] ‚úÖ App started
2025-04-07 02:31:36,898 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 02:50:37,539 [INFO] ‚úÖ App started
2025-04-07 02:50:37,540 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 03:06:31,746 [INFO] ‚úÖ App started
2025-04-07 03:06:31,747 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 03:09:23,054 [ERROR] ‚ùó Error occurred: unsupported operand type(s) for /: 'str' and 'float'
2025-04-07 03:16:42,076 [INFO] ‚úÖ App started
2025-04-07 03:16:42,078 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 03:21:41,945 [ERROR] ‚ùó Error occurred: 'enumerate' is undefined
2025-04-07 03:27:57,502 [ERROR] ‚ùó Error occurred: 'enumerate' is undefined
2025-04-07 03:35:27,977 [ERROR] ‚ùó Error occurred: Encountered unknown tag 'endif'.
2025-04-07 03:35:32,870 [ERROR] ‚ùó Error occurred: Encountered unknown tag 'endif'.
2025-04-07 03:57:45,899 [INFO] ‚úÖ App started
2025-04-07 03:57:45,900 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 04:12:31,282 [INFO] ‚úÖ App started
2025-04-07 04:12:31,283 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 04:27:06,452 [INFO] ‚úÖ App started
2025-04-07 04:27:06,453 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 04:28:23,661 [ERROR] ‚ùó Error occurred: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-04-07 04:56:58,442 [INFO] ‚úÖ App started
2025-04-07 04:56:58,443 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 05:03:06,161 [INFO] ‚úÖ App started
2025-04-07 05:03:06,162 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 05:13:16,096 [INFO] ‚úÖ App started
2025-04-07 05:13:16,098 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 05:13:23,943 [ERROR] ‚ùó Error occurred: name 'tickers' is not defined
2025-04-07 05:15:22,572 [INFO] ‚úÖ App started
2025-04-07 05:15:22,574 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 05:21:39,152 [INFO] ‚úÖ App started
2025-04-07 05:21:39,153 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 05:21:55,084 [ERROR] ‚ùó Error occurred: name 'entry' is not defined
2025-04-07 05:23:02,029 [INFO] ‚úÖ App started
2025-04-07 05:23:02,029 [INFO] ‚úÖ Starting status_updater thread
2025-04-07 05:23:15,517 [ERROR] ‚ùó Error occurred: name 'tickers' is not defined
2025-04-07 05:24:08,971 [INFO] ‚úÖ App started
2025-04-07 05:24:08,973 [INFO] ‚úÖ Starting status_updater thread
